# Generated by Django 2.2.1 on 2019-05-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('hname', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('zipcode', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('phno', models.BigIntegerField()),
                ('uname', models.CharField(max_length=50)),
            ],
        ),
    ]
