# Generated by Django 2.2.1 on 2019-06-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='encrypt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('file', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='blockrc2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=500)),
                ('encrypt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='blockdes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=500)),
                ('encrypt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='blockaes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=500)),
                ('encrypt', models.IntegerField()),
            ],
        ),
    ]
