# Generated by Django 2.2.1 on 2019-06-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_blockaes_blockdes_blockrc2_encrypt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encrypt',
            old_name='file',
            new_name='fid',
        ),
    ]
