# Generated by Django 2.2.1 on 2020-01-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190607_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockaes',
            name='block',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blockdes',
            name='block',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blockrc2',
            name='block',
            field=models.TextField(),
        ),
    ]
