# Generated by Django 2.2.1 on 2020-01-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20200111_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField()),
                ('amt', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='blockaes',
            name='encrypt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blockdes',
            name='encrypt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blockrc2',
            name='encrypt',
            field=models.IntegerField(),
        ),
    ]
