# Generated by Django 2.2.1 on 2020-01-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20200128_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='payment1',
        ),
    ]
